"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Bot, CalendarDays, Check, CheckCircle2, Clock3, Cpu, Laptop, MapPin, RadioTower, ShieldCheck, Users } from "lucide-react";
import { AORS, BATCHES, type Batch } from "@/lib/batches";

type Step="landing"|"aor"|"batch"|"register"|"confirm";
type Draft={fullName:string;rank:string;unit:string;email:string;contactNumber:string;serviceCategory:string;consent:boolean};
type Registration=Draft&{referenceNumber:string;aor:string;batchId:string};
const emptyDraft:Draft={fullName:"",rank:"",unit:"",email:"",contactNumber:"",serviceCategory:"",consent:false};

function Mark(){return <div className="grid h-12 w-12 shrink-0 place-items-center border border-yellow-400/60 bg-emerald-950 text-sm font-black tracking-widest text-yellow-300">TSS</div>}
function Header({step,go}:{step:Step;go:(s:Step)=>void}){
 const back=step==="aor"?"landing":step==="batch"?"aor":"batch";
 return <header className="sticky top-0 z-30 border-b border-white/10 bg-[#043421]/95 text-white backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6">
  <button onClick={()=>go("landing")} className="flex items-center gap-3 text-left" aria-label="Back to Home"><Mark/><span><strong className="block text-base tracking-wide sm:text-lg">THE SIGNAL SCHOOL</strong><small className="block text-[11px] uppercase tracking-[.14em] text-emerald-100">Signal Regiment, Philippine Army</small></span></button>
  {step!=="landing"&&<button onClick={()=>go(back)} className="flex min-h-11 items-center gap-2 rounded-lg border border-white/20 px-3 py-2 text-sm font-semibold hover:bg-white/10"><ArrowLeft size={16}/> Back</button>}
 </div></header>
}
function Progress({step}:{step:Step}){const idx=["aor","batch","register","confirm"].indexOf(step);return <div className="mx-auto mb-8 grid max-w-3xl grid-cols-4 gap-2" aria-label="Registration progress">{["1 AOR","2 Batch","3 Registration","4 Confirmation"].map((x,i)=><div key={x} className="text-center"><div className={`mx-auto mb-2 h-1.5 rounded-full ${i<=idx?"bg-[#0b7543]":"bg-slate-200"}`}/><span className={`text-[11px] font-bold uppercase tracking-wide sm:text-xs ${i<=idx?"text-[#075b32]":"text-slate-400"}`}>{x}</span></div>)}</div>}

export default function Home(){
 const [step,setStep]=useState<Step>("landing"),[aorCode,setAorCode]=useState(""),[batchId,setBatchId]=useState("");
 const [draft,setDraft]=useState<Draft>(emptyDraft),[confirmation,setConfirmation]=useState<Registration|null>(null);
 const batches=useMemo(()=>BATCHES.filter(b=>b.aorCode===aorCode&&b.enabled),[aorCode]);
 const selected=BATCHES.find(b=>b.batchId===batchId);
 function chooseAor(code:string){setAorCode(code);setBatchId("");setStep("batch")}
 return <div className="min-h-screen"><Header step={step} go={setStep}/>
  {step==="landing"?<Landing onStart={()=>setStep("aor")}/>:<main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Progress step={step}/>
   {step==="aor"&&<AorSelection onSelect={chooseAor}/>}
   {step==="batch"&&<BatchSelection aorCode={aorCode} batches={batches} onSelect={id=>{setBatchId(id);setStep("register")}}/>}
   {step==="register"&&selected&&<RegistrationForm batch={selected} draft={draft} setDraft={setDraft} onDone={data=>{setConfirmation(data);setStep("confirm")}}/>}
   {step==="confirm"&&confirmation&&<Confirmation data={confirmation}/>}
  </main>}
  <Footer/>
 </div>
}

function Landing({onStart}:{onStart:()=>void}){return <main>
 <section className="relative overflow-hidden bg-[#062d20] text-white"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(120deg,transparent_45%,#1e8d58_45%,#1e8d58_46%,transparent_46%),radial-gradient(circle_at_80%_20%,#d8a62b_0,transparent_30%)]"/>
  <div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-[1.35fr_.65fr] md:py-16"><div>
   <div className="mb-5 inline-flex items-center gap-2 border-l-4 border-yellow-400 bg-white/10 px-4 py-2 text-sm font-bold uppercase tracking-wider"><ShieldCheck size={18}/> TESDA Certification Opportunity</div>
   <h1 className="max-w-4xl text-4xl font-black uppercase leading-[1.04] tracking-tight sm:text-5xl lg:text-[3.5rem]">Artificial Intelligence Fundamentals and Applications</h1>
   <p className="mt-3 text-xl font-bold text-yellow-300 sm:text-2xl">In-House Training (AIFAT)</p>
   <p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-50">Building AI-ready signalers through the practical and responsible use of generative AI, automation, data privacy, and ethics.</p>
   <button onClick={onStart} className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-lg border-2 border-yellow-500 bg-[#0c7a45] px-6 py-3 font-bold text-white shadow-lg hover:bg-[#09693b]">Select your AOR <ArrowRight size={19}/></button>
  </div><aside className="self-end border border-white/15 bg-black/20 p-6 backdrop-blur"><RadioTower className="mb-5 text-yellow-300" size={42}/><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-200">Conducted by</p><h2 className="mt-2 text-2xl font-black">The Signal School</h2><p className="mt-3 leading-7 text-emerald-50">In collaboration with a TESDA-accredited training provider.</p><p className="mt-4 border-t border-white/15 pt-4 text-sm text-emerald-100">Successful completers may qualify for the corresponding TESDA certification, subject to applicable requirements.</p></aside></div>
 </section>
 <section id="training" className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><p className="text-sm font-black uppercase tracking-[.2em] text-[#0b7543]">Training at a glance</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
  {[[CalendarDays,"5 Days","Training Duration"],[Clock3,"36 Academic Periods","Academic Requirement"],[Bot,"Generative AI","Training Area"],[Cpu,"AI-Enabled Automation","Training Area"],[ShieldCheck,"Data Privacy and Ethics","Training Area"]].map(([I,a,b])=>{const Icon=I as typeof CalendarDays;return <article key={a as string} className="border-t-4 border-[#0b7543] bg-white p-5 shadow-sm"><Icon className="text-[#0b7543]"/><h3 className="mt-4 font-black uppercase">{a as string}</h3><p className="mt-1 text-sm text-slate-600">{b as string}</p></article>})}
 </div></section>
 <section id="about" className="bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#0b7543]">About the training</p><h2 className="mt-3 text-3xl font-black">Responsible AI capability for the workplace</h2></div><p className="text-lg leading-8 text-slate-700">AIFAT is a five-day training designed to develop the fundamental knowledge and practical skills of personnel in the effective and responsible use of Artificial Intelligence tools. It develops responsible AI-enabled users capable of applying available AI tools to selected workplace tasks while maintaining human judgment and accountability.</p></div></section>
 <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><p className="text-sm font-black uppercase tracking-[.2em] text-[#0b7543]">Key training areas</p><div className="mt-5 grid gap-4 lg:grid-cols-3">
  {[[Bot,"Generative AI","Access and interact with generative AI tools, develop and refine prompts, and evaluate AI-generated outputs for workplace applications."],[Cpu,"AI-Enabled Automation","Identify tasks suitable for automation and configure, test, monitor, and update basic AI-enabled workflows."],[ShieldCheck,"Data Privacy and Ethics","Apply responsible AI use, data privacy, security, fairness, transparency, and accountability in the use of AI tools."]].map(([I,a,b])=>{const Icon=I as typeof Bot;return <article key={a as string} className="rounded-xl bg-[#073b27] p-6 text-white"><Icon className="text-yellow-300" size={32}/><h3 className="mt-5 text-xl font-black uppercase">{a as string}</h3><p className="mt-3 leading-7 text-emerald-50">{b as string}</p></article>})}
 </div><div className="mt-8 flex flex-col items-start justify-between gap-4 border-l-4 border-yellow-500 bg-emerald-50 p-5 sm:flex-row sm:items-center"><p className="max-w-3xl font-semibold text-emerald-950">Ready to register? Select the AOR where your unit belongs to view authorized AIFAT batches.</p><button onClick={onStart} className="flex min-h-12 shrink-0 items-center gap-2 rounded-lg bg-[#075b32] px-5 py-3 font-bold text-white">Select your AOR <ArrowRight size={18}/></button></div></section>
 </main>}

function AorSelection({onSelect}:{onSelect:(code:string)=>void}){return <section><p className="text-sm font-black uppercase tracking-[.18em] text-[#0b7543]">Step 1</p><h1 className="mt-2 text-3xl font-black uppercase">Select Your Area of Responsibility (AOR)</h1><p className="mt-2 text-slate-600">Select the AOR where your unit belongs to view the available AIFAT training batches.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{AORS.map(({name,code})=><button key={code} onClick={()=>onSelect(code)} className={`group min-h-28 rounded-xl border-2 bg-white p-4 text-left shadow-sm hover:border-[#0b7543] hover:shadow-md ${code==="T"?"border-yellow-500":"border-slate-200"}`}><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Area of Responsibility</span><strong className="mt-2 block text-xl group-hover:text-[#075b32]">{name}</strong>{code==="T"&&<span className="mt-2 block text-xs font-bold text-[#075b32]">Online and Face-to-Face</span>}</button>)}</div></section>}

function BatchSelection({aorCode,batches,onSelect}:{aorCode:string;batches:Batch[];onSelect:(id:string)=>void}){const aor=AORS.find(a=>a.code===aorCode);return <section><div className="rounded-lg bg-slate-100 p-4"><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Selected AOR</span><strong className="ml-3 text-lg">{aor?.name}</strong></div><h1 className="mt-7 text-3xl font-black uppercase">Available Training Batches</h1><p className="mt-2 text-slate-600">{aorCode==="T"?"Online and face-to-face batches are available for NCR AOR.":"Only Online AM and Online PM batches are authorized for this AOR."}</p><div className="mt-7 grid gap-4 md:grid-cols-2">{batches.map(batch=><BatchCard key={batch.batchId} batch={batch} onSelect={()=>onSelect(batch.batchId)}/>)}</div></section>}
function BatchCard({batch,onSelect}:{batch:Batch;onSelect:()=>void}){const canRegister=batch.status==="OPEN"||batch.status==="NEARLY FULL";return <article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-[#0b7543]">{batch.classDesignation}</p><h2 className="mt-1 text-xl font-black">{batch.deliveryMode} {batch.session}</h2></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-900">{batch.status}</span></div><dl className="mt-5 grid gap-3 text-sm text-slate-700"><div className="flex gap-2"><CalendarDays size={18}/><span>{batch.startDate}–{batch.endDate}</span></div><div className="flex gap-2"><Clock3 size={18}/><span>{batch.startTime}–{batch.endTime}</span></div><div className="flex gap-2"><MapPin size={18}/><span>{batch.venue}</span></div><div className="flex gap-2"><Users size={18}/><span>Maximum capacity: {batch.capacity??"To be announced"}</span></div><div><strong>Registration deadline:</strong> {batch.registrationDeadline??"To be announced"}</div></dl><button disabled={!canRegister} onClick={onSelect} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#075b32] px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-400">Select this batch <ArrowRight size={18}/></button></article>}

function RegistrationForm({batch,draft,setDraft,onDone}:{batch:Batch;draft:Draft;setDraft:(d:Draft)=>void;onDone:(r:Registration)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 function change(name:keyof Draft,value:string|boolean){setDraft({...draft,[name]:value})}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...draft,aor:batch.aorCode,batchId:batch.batchId})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Registration could not be completed.");onDone(data.registration)}catch(err){setError(err instanceof Error?err.message:"Registration could not be completed.");setBusy(false)}}
 const requirements=batch.deliveryMode==="Online"?["Laptop or desktop meeting the prescribed requirements","Stable internet connection","Valid email address","Access to prescribed online platforms"]:["Bring your own laptop meeting the prescribed requirements","Laptop charger or power adapter","Other requirements subsequently prescribed by TSS"];
 return <section><p className="text-sm font-black uppercase tracking-[.18em] text-[#0b7543]">Step 3</p><h1 className="mt-2 text-3xl font-black uppercase">Learner Registration</h1><div className="mt-7 grid gap-6 lg:grid-cols-[.4fr_.6fr]"><aside className="h-fit rounded-xl bg-[#073b27] p-6 text-white"><Laptop className="text-yellow-300"/><p className="mt-4 text-sm font-bold text-emerald-200">{batch.classDesignation}</p><h2 className="mt-1 text-xl font-black">{batch.deliveryMode} {batch.session}</h2><dl className="mt-5 space-y-3 border-t border-white/15 pt-5 text-sm"><div><dt className="text-emerald-200">AOR</dt><dd>{batch.aorName}</dd></div><div><dt className="text-emerald-200">Training dates</dt><dd>{batch.startDate}–{batch.endDate}</dd></div><div><dt className="text-emerald-200">Time</dt><dd>{batch.startTime}–{batch.endTime}</dd></div><div><dt className="text-emerald-200">Venue</dt><dd>{batch.venue}</dd></div></dl><h3 className="mt-6 font-black uppercase">Requirements</h3><ul className="mt-2 space-y-2 text-sm text-emerald-50">{requirements.map(x=><li key={x} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-yellow-300"/>{x}</li>)}</ul></aside>
 <form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-5 sm:grid-cols-2">{[["fullName","Full Name","text","DELA CRUZ, JUAN P."],["rank","Rank","text","CPT"],["unit","Unit / Organization","text","Signal Regiment, PA"],["email","Email Address","email","name@example.com"],["contactNumber","Contact Number","tel","09XX XXX XXXX"]].map(([n,l,t,p])=><label key={n} className={n==="fullName"?"sm:col-span-2":""}><span className="mb-2 block text-sm font-bold">{l} *</span><input name={n} value={String(draft[n as keyof Draft])} onChange={e=>change(n as keyof Draft,e.target.value)} type={t} placeholder={p} required maxLength={100} pattern={n==="contactNumber"?"[0-9+() -]{7,20}":undefined} className="min-h-12 w-full rounded-lg border border-slate-300 px-3"/></label>)}<label><span className="mb-2 block text-sm font-bold">Service Category *</span><select value={draft.serviceCategory} onChange={e=>change("serviceCategory",e.target.value)} required className="min-h-12 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="" disabled>Select category</option><option>Officer</option><option>Enlisted Personnel</option><option>Civilian Human Resource</option></select></label></div>
 <details className="mt-6 rounded-lg bg-slate-50 p-4"><summary className="cursor-pointer font-bold text-[#075b32]">Data Privacy Notice</summary><p className="mt-3 text-sm leading-6 text-slate-700">Personal information is collected and processed for legitimate training administration, learner records, coordination, assessment, certification, and related authorized purposes, subject to applicable Philippine data privacy requirements.</p></details>
 <label className="mt-5 flex gap-3 text-sm leading-6"><input type="checkbox" checked={draft.consent} onChange={e=>change("consent",e.target.checked)} required className="mt-1 h-5 w-5 accent-[#075b32]"/><span>I have read and acknowledge the Data Privacy Notice and confirm that the information provided is correct.</span></label>{error&&<div role="alert" aria-live="assertive" className="mt-5 rounded-lg bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>}<button disabled={busy} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#075b32] px-5 py-3 font-bold text-white disabled:opacity-60">{busy?"Submitting…":"Submit Registration"}<ArrowRight size={18}/></button></form></div></section>}

function Confirmation({data}:{data:Registration}){const b=BATCHES.find(x=>x.batchId===data.batchId)!;return <section className="mx-auto max-w-3xl"><div className="rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm sm:p-10"><div className="text-center"><CheckCircle2 className="mx-auto text-[#0b7543]" size={64}/><p className="mt-4 text-sm font-black uppercase tracking-[.18em] text-[#0b7543]">Registration Successful</p><h1 className="mt-2 text-3xl font-black">You are registered for AIFAT</h1><p className="mt-2 text-slate-600">Your registration has been recorded. Retain your reference number and monitor your registered email address for further training instructions.</p></div><div className="mt-8 rounded-xl bg-slate-50 p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Reference Number</p><p className="mt-1 break-all text-2xl font-black tracking-wide text-[#075b32]">{data.referenceNumber}</p><dl className="mt-6 grid gap-x-6 gap-y-4 text-sm sm:grid-cols-2">{[["Learner Name",data.fullName],["Rank",data.rank],["Unit / Organization",data.unit],["AOR",b.aorName],["Class Designation",b.classDesignation],["Delivery Mode",b.deliveryMode],["Session",b.session],["Training Dates",`${b.startDate}–${b.endDate}`],["Training Time",`${b.startTime}–${b.endTime}`],["Venue",b.venue]].map(([k,v])=><div key={k}><dt className="font-bold text-slate-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl></div><button onClick={()=>window.print()} className="mt-7 flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#075b32] px-5 py-3 font-bold text-white"><Check size={18}/> Print / Save Confirmation</button></div></section>}
function Footer(){return <footer className="mt-12 border-t-4 border-yellow-500 bg-[#032d1d] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-7 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-3"><Mark/><div><strong>THE SIGNAL SCHOOL</strong><p className="text-xs text-emerald-100">Fort Andres Bonifacio, Taguig City</p></div></div><p className="text-sm font-bold uppercase tracking-[.16em] text-yellow-300">Honor. Patriotism. Duty.</p></div></footer>}
